name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/random-quotes-app
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Deploy Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

        script: |
          cd ~/random-quotes-app
          
          # Stop and remove existing container
          docker stop random-quotes-container || true
          docker rm random-quotes-container || true
          
          # Pull the latest image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/random-quotes-app:latest
          
          echo "${{ secrets.ENV}}" > .env
          
          # Run the container with environment variables
          docker run -d \
            --name random-quotes-container \
            -p 8080:8080 \
            --env-file .env \
            ${{ secrets.DOCKER_USERNAME }}/random-quotes-app